//AUTOGENERATED FILE FROM png2asset
// Conversion args: /Font.png -c /Font.c -map -keep_palette_order -noflip

#ifndef METASPRITE_Font_H
#define METASPRITE_Font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Font_TILE_ORIGIN 0
#define Font_TILE_W 8
#define Font_TILE_H 8
#define Font_WIDTH 208
#define Font_HEIGHT 16
#define Font_TILE_COUNT 46
#define Font_PALETTE_COUNT 4
#define Font_COLORS_PER_PALETTE 4
#define Font_TOTAL_COLORS 16
#define Font_MAP_ATTRIBUTES 0
extern const unsigned char Font_map[52];
#define Font_map_attributes Font_map

BANKREF_EXTERN(Font)

extern const palette_color_t Font_palettes[16];
extern const uint8_t Font_tiles[736];

#endif
