//AUTOGENERATED FILE FROM png2asset
// Conversion args: gameover.png -keep_duplicate_tiles

#ifndef METASPRITE_gameover_H
#define METASPRITE_gameover_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gameover_TILE_ORIGIN 0
#define gameover_TILE_W 8
#define gameover_TILE_H 16
#define gameover_WIDTH 64
#define gameover_HEIGHT 32
#define gameover_TILE_COUNT 32
#define gameover_PALETTE_COUNT 1
#define gameover_COLORS_PER_PALETTE 4
#define gameover_TOTAL_COLORS 4
#define gameover_PIVOT_X 32
#define gameover_PIVOT_Y 16
#define gameover_PIVOT_W 64
#define gameover_PIVOT_H 32
extern const metasprite_t* const gameover_metasprites[1];

BANKREF_EXTERN(gameover)

extern const palette_color_t gameover_palettes[4];
extern const uint8_t gameover_tiles[512];

#endif
