//AUTOGENERATED FILE FROM png2asset
// Conversion args: ibm_minimal_dark.png -spr8x8 -keep_palette_order

#ifndef METASPRITE_ibm_minimal_dark_H
#define METASPRITE_ibm_minimal_dark_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ibm_minimal_dark_TILE_ORIGIN 0
#define ibm_minimal_dark_TILE_W 8
#define ibm_minimal_dark_TILE_H 8
#define ibm_minimal_dark_WIDTH 128
#define ibm_minimal_dark_HEIGHT 24
#define ibm_minimal_dark_TILE_COUNT 48
#define ibm_minimal_dark_PALETTE_COUNT 1
#define ibm_minimal_dark_COLORS_PER_PALETTE 4
#define ibm_minimal_dark_TOTAL_COLORS 4
#define ibm_minimal_dark_PIVOT_X 64
#define ibm_minimal_dark_PIVOT_Y 12
#define ibm_minimal_dark_PIVOT_W 128
#define ibm_minimal_dark_PIVOT_H 24
extern const metasprite_t* const ibm_minimal_dark_metasprites[1];

BANKREF_EXTERN(ibm_minimal_dark)

extern const palette_color_t ibm_minimal_dark_palettes[4];
extern const uint8_t ibm_minimal_dark_tiles[768];

#endif
