//AUTOGENERATED FILE FROM png2asset
// Conversion args: ibm_minimal.png -spr8x8

#ifndef METASPRITE_ibm_minimal_H
#define METASPRITE_ibm_minimal_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ibm_minimal_TILE_ORIGIN 0
#define ibm_minimal_TILE_W 8
#define ibm_minimal_TILE_H 8
#define ibm_minimal_WIDTH 128
#define ibm_minimal_HEIGHT 24
#define ibm_minimal_TILE_COUNT 47
#define ibm_minimal_PALETTE_COUNT 1
#define ibm_minimal_COLORS_PER_PALETTE 4
#define ibm_minimal_TOTAL_COLORS 4
#define ibm_minimal_PIVOT_X 64
#define ibm_minimal_PIVOT_Y 12
#define ibm_minimal_PIVOT_W 128
#define ibm_minimal_PIVOT_H 24
extern const metasprite_t* const ibm_minimal_metasprites[1];

BANKREF_EXTERN(ibm_minimal)

extern const palette_color_t ibm_minimal_palettes[4];
extern const uint8_t ibm_minimal_tiles[752];

#endif
