//AUTOGENERATED FILE FROM png2asset
// Conversion args: start_screen.png -map

#ifndef METASPRITE_start_screen_H
#define METASPRITE_start_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define start_screen_TILE_ORIGIN 0
#define start_screen_TILE_W 8
#define start_screen_TILE_H 8
#define start_screen_WIDTH 160
#define start_screen_HEIGHT 144
#define start_screen_TILE_COUNT 59
#define start_screen_PALETTE_COUNT 1
#define start_screen_COLORS_PER_PALETTE 4
#define start_screen_TOTAL_COLORS 4
#define start_screen_MAP_ATTRIBUTES 0
extern const unsigned char start_screen_map[360];
#define start_screen_map_attributes start_screen_map

BANKREF_EXTERN(start_screen)

extern const palette_color_t start_screen_palettes[4];
extern const uint8_t start_screen_tiles[944];

#endif
