//AUTOGENERATED FILE FROM png2asset
// Conversion args: tiles_empty.png -keep_duplicate_tiles

#ifndef METASPRITE_tiles_empty_H
#define METASPRITE_tiles_empty_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_empty_TILE_ORIGIN 0
#define tiles_empty_TILE_W 8
#define tiles_empty_TILE_H 16
#define tiles_empty_WIDTH 16
#define tiles_empty_HEIGHT 16
#define tiles_empty_TILE_COUNT 4
#define tiles_empty_PALETTE_COUNT 1
#define tiles_empty_COLORS_PER_PALETTE 4
#define tiles_empty_TOTAL_COLORS 4
#define tiles_empty_PIVOT_X 8
#define tiles_empty_PIVOT_Y 8
#define tiles_empty_PIVOT_W 16
#define tiles_empty_PIVOT_H 16
extern const metasprite_t* const tiles_empty_metasprites[1];

BANKREF_EXTERN(tiles_empty)

extern const palette_color_t tiles_empty_palettes[4];
extern const uint8_t tiles_empty_tiles[64];

#endif
